name: Build

on: [push, pull_request]
jobs:
  go:
    name: go build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: install dep
        run: |
          go get -d -v
      - name: build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o .
      - name: Archive production artifacts
        if: contains(github.ref, 'main')
        uses: actions/upload-artifact@v1
        with:
          name: backend
          path: backend/e-book-manager
  yarn:
    name: cache node modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache-node-modules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-cache-node-modules-${{ hashFiles('frontend/yarn.lock') }}
      - name: Yarn install if cache is invalid
        if: steps.yarn-cache-node-modules.outputs.cache-hit != 'true'
        working-directory: ./frontend
        run: yarn install
  lint:
    name: lint frontend
    runs-on: ubuntu-latest
    needs: [ yarn ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache-node-modules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-cache-node-modules-${{ hashFiles('frontend/yarn.lock') }}
      - name: lint
        working-directory: ./frontend
        run: npm run lint
  build:
    name: build frontend
    runs-on: ubuntu-latest
    needs: [ yarn ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache-node-modules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-cache-node-modules-${{ hashFiles('frontend/yarn.lock') }}
      - name: build vite
        working-directory: ./frontend
        run: npm run build
      - name: Archive production artifacts
        if: contains(github.ref, 'main')
        uses: actions/upload-artifact@v1
        with:
          name: frontend
          path: frontend/dist
  docker:
    name: build docker
    runs-on: ubuntu-latest
    needs: [ build, go, lint ]
    if: contains(github.ref, 'main')
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: ./docker
      - name: Build image
        working-directory: ./docker
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/e-book-manager
      - name: push image
        run: |
          docker login -u=${{ secrets.DOCKER_USER }} -p=${{ secrets.DOCKER_PASSWORD }}
          docker tag ${{ secrets.DOCKER_USER }}/e-book-manager ${{ secrets.DOCKER_USER }}/e-book-manager:latest
          docker push ${{ secrets.DOCKER_USER }}/e-book-manager:latest
          docker tag ${{ secrets.DOCKER_USER }}/e-book-manager ${{ secrets.DOCKER_USER }}/e-book-manager:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USER }}/e-book-manager:${{ github.run_number }}
  docker-dev:
    name: build docker
    runs-on: ubuntu-latest
    needs: [ build, go, lint ]
    if: contains(github.ref, 'feature')
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: ./docker
      - name: Build image
        working-directory: ./docker
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/e-book-manager
      - name: push image
        run: |
          docker login -u=${{ secrets.DOCKER_USER }} -p=${{ secrets.DOCKER_PASSWORD }}
          docker tag ${{ secrets.DOCKER_USER }}/e-book-manager ${{ secrets.DOCKER_USER }}/e-book-manager:${{ github.run_number }}-dev
          docker push ${{ secrets.DOCKER_USER }}/e-book-manager:${{ github.run_number }}-dev
